; 生成大量符号相关操作，用来观察 symbol intern 表的扩张行为。
(set i 0)
(while (< i 10000)
  (set s (quote placeholder))
  ;; constructs like (set sN 0) are generated by the preprocessor below,
  ;; but here we just create unique symbol literals by placing many (set s0 0) lines
)
