; generate many unique symbol bindings to stress symbol_intern
(set i 0)
(while (< i 10000)
  (set s (quote placeholder))
  ;; constructs like (set sN 0) are generated by the preprocessor below,
  ;; but here we just create unique symbol literals by placing many (set s0 0) lines
)
