(set i 0)
(while (< i 20000)
  (set tmp (list))
  (set k 0)
  (while (< k 200)
    (set tmp (cons (list k) tmp))
    (set k (+ k 1)))
  (set fns (list))
  (set k 0)
  (while (< k 200)
    (set fns (cons (fn (x) (+ x 1)) fns))
    (set k (+ k 1)))
  ;; overwrite tmp/fns each iteration to allow releases
  (set i (+ i 1))
)
(print "done")
